version: "3"

services:

    fluent_bit:
        image: fluent/fluent-bit:latest
        networks:
            - fix
        volumes: 
            - ./Logs:/fluent-bit/log
            - ./fluentconfig.conf:/fluent-bit/etc/fluent-bit.conf
        ports:
            - "24224:24224"
            

    auto_log_generator:
        image: app_logger:latest
        tty: true
        networks:
            - fix
        ports:
            - "80:80"
        logging:
            driver: "fluentd"
        deploy: 
            replicas: 5

networks:
    fix:
        driver: overlay

