name: Femi - Callable_Workflow

on:
  workflow_call:
    inputs:
      Command:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      rule_name:
        required: true
        type: string
      author:
        required: true
        type: string

jobs:
  test_mic_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a command
        run: echo "This workflow was triggered manually."
      - name: Print the GitHub event to differntiate
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.ref_base }}"
          echo "Actor: ${{ github.actor }}"
